### ISSUE TITLE
Notify on successful download

### ISSUE THREAD

**Issue by paulpopus** [cristianovitorino/figwrapper#9]
When you export assets, it does download them to the system's default download folder but there isn't any popup or notification letting you know that it's been downloaded.

**Comment by cristianovitorino** [comment]
Hey @paulpopus thanks for reporting. For that I would have to program listeners/watchers to interface with the Figma web app itself, I'm unable to do that and it is beyond the scope of the this project.

Plus, this is the expected behavior, think of it as a web browser, which it actually kinda is, an instantiated single window web browser, web browsers download files, by default, to your Downloads folder.
